name: fit-diff
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - pandas
  - pip
  - plotly=5.24.1
  - pyyaml
  - pytest
  - python-dotenv
  - python-duckdb
  - python=3.12.10
  - shinywidgets=0.6.2
  - scipy
  - aiohttp
  - requests
  - httpx
  - ipykernel
  - nbformat
  - aioboto3
  - pip:
      - shiny==1.4.0
      - shinyswatch==0.9.0
      - fitparse
      - garmin-fit-sdk==21.171.0
      - faicons==0.2.2
      - nbformat>=4.2.0
